"""service boards

Revision ID: 09e9fa4fc419
Revises: 7973fc15ad2f
Create Date: 2026-06-03 08:15:42.663850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09e9fa4fc419'
down_revision: Union[str, None] = '7973fc15ad2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_boards_id'), ['id'], unique=False)

    # Add the board_id column. We deliberately do NOT rebuild the tickets table
    # to create named FKs: SQLite doesn't enforce FKs, and Postgres keeps the
    # relationship via the model. A plain add_column is portable to both.
    op.add_column('tickets', sa.Column('board_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column('tickets', 'board_id')
    op.drop_table('boards')
